### ISSUE TITLE
Error in users list (role)

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-desk#59]
При просмотре деталей пользователя с ролью менеджер (при выходе из режима редактирования записи):
```
vue.global.prod.js:1 TypeError: Cannot set properties of null (setting 'role')
    at Proxy.fldRole (Edit.mjs:287:52)
    at Lt (vue.global.prod.js:1:14348)
    at jt (vue.global.prod.js:1:14426)
    at f (vue.global.prod.js:1:23299)
    at Lt (vue.global.prod.js:1:14356)
    at sn (vue.global.prod.js:1:15886)
...
vue.global.prod.js:1 TypeError: Cannot set properties of null (setting 'state')
    at Proxy.fldActive (Edit.mjs:284:53)
    at Lt (vue.global.prod.js:1:14348)
    at jt (vue.global.prod.js:1:14426)
    at f (vue.global.prod.js:1:23299)
    at Lt (vue.global.prod.js:1:14356)
    at sn (vue.global.prod.js:1:15886)
```

**Comment by flancer64** [comment]
Ошибки появляются, когда нажимаешь на кнопку "Закрыть", а не закрываешь диалог через escape или кликом по серому фону.
